spring:
  security:
    oauth2:
      client:
        registration:
          oauth-client:
            provider: servidor-autorizacion
            client-id: oauth-client
            client-name: oauth-client
            client-secret: 12345678910
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:8080/authorized"
            scope: openid,profile,read,write
        provider:
          servidor-autorizacion:
            issuer-uri: http://localhost:9000
